[WIP] Subquery
futil-js/contexture-core pull request #15
Opened 2018-05-23 01:30 UTC by daedalus28

Support for subquery in contexture core

2018-05-23 01:31 UTC, decrapifier commented
<!--
  2 failure:  The changelog has..., The version was n...
  1 warning:  The README has no...
  2 messages
  
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  The changelog has not been updated. Please update the changelog.
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  The version was not updated. Please update the version.
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  The README has not been updated. Please update the README.
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  You reduced the total lines of code! Awesome! :+1:
  </td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>

  We were able to automatically fix some formatting issues in this PR for you!
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-05-23 17:44 UTC, sadasant requested changes

2018-05-23 17:44 UTC, sadasant commented on src/index.js
>    async (getProvider, processor, item, ...args) => {
This function needs documentation 📚. Something along the lines of:
> runTypeProcessor tries to find and execute the processor function available for the provided item type. If the item type is not found among the types that exist within the provider obtained by getProvider, or if the processor is not present in that type, this function will not do any processing and will return undefined.

2018-05-23 17:44 UTC, sadasant commented on src/index.js
> +let walkAsync = tree => f => parentFirstDFS(getChildren, f, tree)
overAsync and walkAsync seem sufficiently generic to live in futil-js 🤖, or at least to live in a utilities file, separate from this file 🌞

2018-05-23 17:44 UTC, sadasant commented on src/index.js
> +          async item => {
To make this block prettier, this async function could have a name 📛

2018-05-25 19:58 UTC, daedalus28 commented
Closing in favor of #17

2018-05-25 19:58 UTC, closed without merging