Throw error object
futil-js/contexture-core pull request #28
Opened 2019-06-20 00:17 UTC by Akrion

Throws now an error object with the actual error as part of it. This is needed for other repos to know the error details.

2019-06-20 00:23 UTC, decrapifier commented
<!--
  0 failure: 
  1 warning:  The README has no...
  1 messages
  
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  The README has not been updated. Please update the README.
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  We were able to automatically fix some formatting issues in this PR for you!
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2019-06-24 17:40 UTC, daedalus28 requested changes

2019-06-24 17:40 UTC, daedalus28 commented on src/utils.js
> +      error,
We should probably put the actual `item` on here too as `node` to make it really easy to inspect

2019-06-24 17:47 UTC, Akrion commented on src/utils.js
> +      error,
Added item

2019-06-24 19:29 UTC, daedalus28 commented on src/utils.js
> +      error: F.extendOn(error, { node: item }),
seems like we could just have `message: '', error, item`

2019-06-24 19:54 UTC, merged