Support array fields in memory provider's facet
futil-js/contexture-core pull request #37
Opened 2020-03-04 20:23 UTC by michsa

Further improvements to the memory provider! Now facet supports array fields like contexture-mongo and contexture-es do 🙂

WIP/draft until https://github.com/smartprocure/futil-js/pull/320 is in - I tested the logic with the new unwind behavior in a runkit and I'm pretty sure it works, but it'll fail our tests until futil is updated.

2020-03-04 20:24 UTC, michsa commented on src/provider-memory/exampleTypes.js
> +          F.mapIndexed((count, name) => ({ name, count })),
this one's just ⛳️

2020-04-13 22:58 UTC, daedalus28 commented
https://github.com/smartprocure/futil-js/pull/320 was merged so this just needs to be updated to use it

2020-07-07 15:55 UTC, decrapifier commented
<!--
  0 failure: 
  1 warning:  The README has no...
  2 messages
  1 markdown notices
  DangerID: danger-id-default;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>The README has not been updated. Please update the README.</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>Could not find any browser results.</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>We were able to automatically fix some formatting issues in this PR for you!</td>
    </tr>
  </tbody>
</table>


### Some things that were possibly fixed:

- Code that could be fixed via the --fix flag
- Formatting that could be fixed by prettier

Take a look at this commit to see what happened in detail: 59127efdec0c3f6406f16a41892314be7e0bf013


And look at this wiki page to see the reasoning behind the ESLint rules: https://github.com/smartprocure/eslint-config-smartprocure/wiki/Rules-and-Why-We-Chose-Them
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 30eb7c101175c7e123a697cf39a0a2e50fb2717b
</p>

2020-07-08 20:28 UTC, daedalus28 requested changes

2020-07-08 20:28 UTC, daedalus28 commented on src/provider-memory/exampleTypes.js
> +          optionsFilter ? _.filter(stringContains(optionsFilter)) : _.identity,
let's make sure stringContains calls JSON.stringify so that this can work properly on objects

2020-07-08 20:28 UTC, daedalus28 commented on src/utils.js
> +let mapCountBy = _.curry((iter, list) => {
if you're going to stringify anyway, you can just a regular _.groupBy

2020-07-10 20:51 UTC, daedalus28 requested changes

2020-07-10 20:51 UTC, daedalus28 commented on test/memory.js
> +          { name: 2, count: 1 },
I'm not sure this change is desirable since this is technically a breaking change since the type is changing 🤔 . In practice, I doubt this breaks any real-world use cases, but we should at least call this out in the changelog.

2020-07-13 21:09 UTC, stellarhoof commented on test/memory.js
> +          { name: 2, count: 1 },
This is what contexture-mongo does btw: https://github.com/smartprocure/contexture-mongo/blob/master/test/example-types/facet.js#L180. I'll update the changelog

2020-07-20 14:21 UTC, merged