Feature/fix memory date type
futil-js/contexture-core pull request #40
Opened 2020-04-07 20:50 UTC by dshishkov

Add support for date math operations on provider-memory date type

2020-04-07 20:57 UTC, decrapifier commented
<!--
  0 failure: 
  1 warning:  The README has no...
  1 messages
  
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  The README has not been updated. Please update the README.
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  Awesome! Thanks for the well-formatted PR!
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2020-04-07 22:01 UTC, daedalus28 approved these changes

2020-04-07 22:01 UTC, daedalus28 requested changes

2020-04-07 22:01 UTC, daedalus28 commented on package.json
> +    "moment": "^2.24.0"
why add moment?

2020-04-07 22:48 UTC, dshishkov commented on package.json
> +    "moment": "^2.24.0"
It seems to be required and assumed to be there by the elastic datemath package. I tried without it but tests failed.

2020-04-08 02:51 UTC, dshishkov commented on package.json
> +    "moment": "^2.24.0"
@daedalus28 it's required here https://github.com/elastic/kibana/blob/master/packages/elastic-datemath/src/index.js#L20 but at the same time they only have in devDependencies instead of dependencies in their package.json

2020-04-08 16:05 UTC, merged