Date Type changes & tests
futil-js/contexture-core pull request #50
Opened 2020-10-28 00:37 UTC by Akrion

- Rolling range now works
- Test cases added for `exact` and `rolling` range 
- Other tests made current with the latest changes
- Filter should not not require the value to be in time format `new Date().getTime()` now. Strings should just work etc.

In regards to #47

2020-10-28 00:38 UTC, decrapifier commented
<!--
  1 failure:  This PR has faili...
  1 warning:  The README has no...
  2 messages
  1 markdown notices
  DangerID: danger-id-default;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>This PR has failing tests. Please alleviate the errors and commit them

<details>
  <summary>next6Months</summary>
  <code>expected { Object (totalRecords, results) } to deeply equal { Object (results, totalRecords) }</code>
</details></td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>The README has not been updated. Please update the README.</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>Could not find any browser results.</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>We were able to automatically fix some formatting issues in this PR for you!</td>
    </tr>
  </tbody>
</table>


### Some things that were possibly fixed:

- Code that could be fixed via the --fix flag
- Formatting that could be fixed by prettier

Take a look at this commit to see what happened in detail: a62501cb34fee05a2b4b4bff70e8a88d92e65681


And look at this wiki page to see the reasoning behind the ESLint rules: https://github.com/smartprocure/eslint-config-smartprocure/wiki/Rules-and-Why-We-Chose-Them
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against ea73a220d142e0b077f94b909b780398961f06c2
</p>

2020-10-28 00:43 UTC, Akrion commented
All tests pass:

![image](https://user-images.githubusercontent.com/910303/97376884-d051d500-187b-11eb-8fa3-d799b0042375.png)

Not sure what the issue is above ...

2020-10-28 19:30 UTC, dubiousdavid requested changes

2020-10-28 19:30 UTC, dubiousdavid commented on src/provider-memory/date.js
> +    let { from, to } = _.includes(range, ['exact', 'allDates'])
This can be just `range === 'exact'`. There is no filtering for `allDates`. There is a mistake in the logic for contexture-mongo and contexture-elasticsearch.

2020-10-28 20:10 UTC, dubiousdavid requested changes

2020-10-28 20:10 UTC, dubiousdavid commented on test/date.js
> +let dates = [
Can you add a comment for each element with the index number so that it's a little clearer how the `expected` indexes correlate?

2020-10-28 20:12 UTC, Akrion commented on test/date.js
> +let dates = [
I simply used `console.table(dates)` ... I can add that

2020-10-28 21:57 UTC, dubiousdavid requested changes
The test are still hard to read and verify. I think we should change `dates` to an object where the key is something meaningful, like `15monthsAgo`, and then verify the named keys instead of array indexes.

2020-10-29 00:49 UTC, dubiousdavid requested changes
This looks, but I'd remove the tests for `thisCalendarYear` and `nextCalendarYear` since those are relative and subject to change depending on where you are in the current calendar year.

2020-10-29 00:49 UTC, dubiousdavid commented on test/date.js
> +        'nextMonth',
`tomorrow` and `nextMonth` won't always pass for this test.

2020-10-29 00:49 UTC, dubiousdavid commented on test/date.js
> +    testRange({ range: 'nextCalendarYear', expected: ['next6Months'] })),
This won't pass if the next calendar year is a year away.

2020-10-29 01:07 UTC, dubiousdavid approved these changes

2020-10-29 01:07 UTC, merged